### ISSUE TITLE
Fixar versão do Ruby para o projeto

### ISSUE THREAD

**Issue by danilolic** [danilolic/mwcrawler#12]
Deve ser criado um arquivo .ruby-version fixando a versão do Ruby para 2.5.1

**Comment by mateusluizfb** [comment]
Posso pegar esse?

**Comment by mateusluizfb** [comment]
Acho que só botar a versão do ruby na gemfile já resolve

**Comment by danilolic** [comment]
O arquivo .ruby-version forçará a rvm usar a versão descrita nele, fazendo a rvm trocar automaticamente para a versão quando dentro do diretório do projeto. O arquivo também é suportado pela  chruby e rbenv.

Acho melhor optar pelo uso do do arquivo .ruby-version nesse caso.
