### ISSUE TITLE
Traduzir README.md

### ISSUE THREAD

**Issue by danilolic** [danilolic/mwcrawler#16]
Traduzir o README

**Comment by wladimirgramacho** [comment]
Oie, to de intruso nessa aqui, mas eu prefiro que coisas relacionadas ao código fiquem em inglês, já que o código é em inglês. Quando formos fazer comentários sobre o código, faz mais sentido se tanto o comentário quanto o código estão no mesmo idioma.

**Comment by danilolic** [comment]
Concordo, mas o README é só as instruções para as pessoas saberem rodar o código. Acho válido ser em Português porque acredito que a maioria das pessoas que clonam o projeto falam Português. Quanto aos comentários de código dentro do projeto que estão em Português: estou ciente e pretendo mudar para Inglês.

Agradeço as sugestões :)
