### ISSUE TITLE
Gema não encontrada para instalação

### ISSUE THREAD

**Issue by wladimirgramacho** [danilolic/mwcrawler#28]
Ao rodar:
`gem install mwcrawler`

Recebo o erro:
`ERROR:  Could not find a valid gem 'mwcrawler' (>= 0) in any repository`

**Comment by danilolic** [comment]
Não está disponível no RubyGems, você precisa passar o path do github para usar. O Readme está bem desatualizado.

**Comment by danilolic** [comment]
Resolvido
